In [1]:
import numpy as np

In [ ]:
#
# HIV/AIDS Example
#

In [3]:
# Stochastic transition matrix
# Columns correspond to: HIV Asymtomatic, HIV Symptomatic, AIDS, Death

trans_matrix = np.array([[.9, .07, .02, .01], [0, .93, .05, .02], [0, 0, .85, .15], [0, 0, 0, 1.0]])
print(trans_matrix.shape)
trans_matrix

(4, 4)


array([[ 0.9 ,  0.07,  0.02,  0.01],
       [ 0.  ,  0.93,  0.05,  0.02],
       [ 0.  ,  0.  ,  0.85,  0.15],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [8]:
# Vector for current health states of a group 
# Rows correspond to: HIV Asymtomatic, HIV Symptomatic, AIDS, Death

current_states = np.array([.85, .1, .05, 0]).reshape(-1, 1)
print(current_states.shape)
current_states

(4, 1)


array([[ 0.85],
       [ 0.1 ],
       [ 0.05],
       [ 0.  ]])

In [9]:
# Calculate % in each health state after 1 year (probabilities in stochastic matrix are for 1 year)

np.dot(trans_matrix.T, current_states)

array([[ 0.765 ],
       [ 0.1525],
       [ 0.0645],
       [ 0.018 ]])

In [10]:
# Alternative way to do dot product (Python 3)

trans_matrix.T @ current_states

array([[ 0.765 ],
       [ 0.1525],
       [ 0.0645],
       [ 0.018 ]])

In [11]:
#
# Shopping example
#

In [12]:
# Demand Matrix

D = np.array([[6,5,3,1], [3,6,2,2], [3,4,3,1]])
print(D.shape)
D   

(3, 4)


array([[6, 5, 3, 1],
       [3, 6, 2, 2],
       [3, 4, 3, 1]])

In [13]:
# Price Matrix

P = np.array([[1.50, 1.00], [2.00, 2.50], [5.00, 4.50], [16.00, 17.00]])
print(P.shape)
P

(4, 2)


array([[  1.5,   1. ],
       [  2. ,   2.5],
       [  5. ,   4.5],
       [ 16. ,  17. ]])

In [14]:
# Multiply D and P 
# Each element of resulting matrix represents total cost to a specific person of shopping at a specific shore

D @ P

array([[ 50. ,  49. ],
       [ 58.5,  61. ],
       [ 43.5,  43.5]])

In [ ]:
#
# Accuracy
#

In [ ]:
# 1.) Floating Point Arithmetic

In [1]:
def f(x):
    if x <= 1/2:
        return 2 * x
    if x > 1/2:
        return 2*x -1

In [2]:
# Notice: Output is not what one would intuitively expect
# Math is continuous and infinite, but computers are discrete and finite
# Computers can't form infinitely accurate numbers 

x = 1/10
for i in range(80):
    print(x)
    x = f(x)

0.1
0.2
0.4
0.8
0.6000000000000001
0.20000000000000018
0.40000000000000036
0.8000000000000007
0.6000000000000014
0.20000000000000284
0.4000000000000057
0.8000000000000114
0.6000000000000227
0.20000000000004547
0.40000000000009095
0.8000000000001819
0.6000000000003638
0.2000000000007276
0.4000000000014552
0.8000000000029104
0.6000000000058208
0.20000000001164153
0.40000000002328306
0.8000000000465661
0.6000000000931323
0.20000000018626451
0.40000000037252903
0.8000000007450581
0.6000000014901161
0.20000000298023224
0.4000000059604645
0.800000011920929
0.6000000238418579
0.20000004768371582
0.40000009536743164
0.8000001907348633
0.6000003814697266
0.20000076293945312
0.40000152587890625
0.8000030517578125
0.600006103515625
0.20001220703125
0.4000244140625
0.800048828125
0.60009765625
0.2001953125
0.400390625
0.80078125
0.6015625
0.203125
0.40625
0.8125
0.625
0.25
0.5
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [ ]:
"""
Floating point arithmetic: how computers store numbers

Floating point numbers have three components: sign, mantissa/sagnificand, and exponent
The base (radix) is usually 2 
The sign is a single bit (0 for positive, 1 for negative )
Machine Epsilon: Half the distance between 1 and the next larger number 

"""



In [ ]:
# 2.) Conditioning and Stability

