In [1]:
import numpy as np

In [ ]:
#
# HIV/AIDS Example
#

In [3]:
# Stochastic transition matrix
# Columns correspond to: HIV Asymtomatic, HIV Symptomatic, AIDS, Death

trans_matrix = np.array([[.9, .07, .02, .01], [0, .93, .05, .02], [0, 0, .85, .15], [0, 0, 0, 1.0]])
print(trans_matrix.shape)
trans_matrix

(4, 4)


array([[ 0.9 ,  0.07,  0.02,  0.01],
       [ 0.  ,  0.93,  0.05,  0.02],
       [ 0.  ,  0.  ,  0.85,  0.15],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [8]:
# Vector for current health states of a group 
# Rows correspond to: HIV Asymtomatic, HIV Symptomatic, AIDS, Death

current_states = np.array([.85, .1, .05, 0]).reshape(-1, 1)
print(current_states.shape)
current_states

(4, 1)


array([[ 0.85],
       [ 0.1 ],
       [ 0.05],
       [ 0.  ]])

In [9]:
# Calculate % in each health state after 1 year (probabilities in stochastic matrix are for 1 year)

np.dot(trans_matrix.T, current_states)

array([[ 0.765 ],
       [ 0.1525],
       [ 0.0645],
       [ 0.018 ]])

In [10]:
# Alternative way to do dot product (Python 3)

trans_matrix.T @ current_states

array([[ 0.765 ],
       [ 0.1525],
       [ 0.0645],
       [ 0.018 ]])

In [11]:
#
# Shopping example
#

In [12]:
# Demand Matrix

D = np.array([[6,5,3,1], [3,6,2,2], [3,4,3,1]])
print(D.shape)
D   

(3, 4)


array([[6, 5, 3, 1],
       [3, 6, 2, 2],
       [3, 4, 3, 1]])

In [13]:
# Price Matrix

P = np.array([[1.50, 1.00], [2.00, 2.50], [5.00, 4.50], [16.00, 17.00]])
print(P.shape)
P

(4, 2)


array([[  1.5,   1. ],
       [  2. ,   2.5],
       [  5. ,   4.5],
       [ 16. ,  17. ]])

In [14]:
# Multiply D and P 
# Each element of resulting matrix represents total cost to a specific person of shopping at a specific shore

D @ P

array([[ 50. ,  49. ],
       [ 58.5,  61. ],
       [ 43.5,  43.5]])